version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: novavaga_postgres
    environment:
      POSTGRES_USER: novavaga
      POSTGRES_PASSWORD: jesus10
      POSTGRES_DB: novavaga
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novavaga -d novavaga"]
      interval: 5s
      retries: 5
      timeout: 5s

  backend:
    build: .
    container_name: novavaga_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://novavaga:jesus10@postgres:5432/novavaga
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: